name: test-deploy
env:
  NAME: 'name-demo'

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: dev
        required: false
jobs:
  env-veriables-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print Name
        run: echo "Hello $NAME"